spring.datasource.url=jdbc:postgresql://localhost:5432/urlshortenerdb
spring.datasource.username=postgres
spring.datasource.password=Gischa22

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true